version: "3.2"
services:
  postgresql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
        - ./.data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=blog_db
    restart: always
    networks:
      - default
networks:
    default:
        driver: bridge
